project:
  type: website
  output-dir: docs        

website:
  title: "MBA Portfolio: Karma Galley"
  repo-url: "https://github.com/<USERNAME>/mba-portfolio-karma"
  page-navigation: false
            

format:
  html:
    theme: cosmo          
    css: styles.css      
    toc: true            