project:
  type: website
  output-dir: docs

website:
  title: "MBA Portfolio: Karma Galley"
  navbar:
    left:
      - text: "Portfolio"
        href: index.html
      - text: "Certificates"
        href: certificates.html
      - text: "Skills"
        href: skills.html
      - text: "Contact"
        href: contact.html




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: scripts.html
