name: Render & Deploy Quarto Site

# Trigger on pushes to main (you can also use tags, PRs, etc.)
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository
    - uses: actions/checkout@v3

    # 2. Set up Quarto CLI
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v3
      with:
        version: '1.5.339'

    # 3. Render the site
    - name: Render Quarto website
      run: quarto render

    # 4. Deploy the docs/ folder to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages           # the branch the action should deploy to
        folder: docs               # folder to deploy
        clean: true
